version: '3'

x-env: &env
  - POSTGRES_USER=root
  - POSTGRES_PASSWORD=password
  - APP_DB_USER=docker
  - APP_DB_PASS=docker
  - APP_DB_NAME=battlesnake  
  - CONTAINER_DB_NAME=battlesnake-database
  - DB_PORT=5432
  - ALG_VERSION=1

services:

  # DATABASE CONTAINER
  database:
    image: "postgres" # use latest official postgres version
    container_name: "battlesnake-database"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment: *env
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  
  # API CONTAINER
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "battlesnake-api"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - database
    environment: *env

